name: Fetch Conjur Secret
 
on:
 workflow_call:
 # push:
 #   branches: [ main ]
 
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Install curl and jq
      run: sudo apt-get update && sudo apt-get install -y curl jq
 
    - name: Authenticate to Conjur and retrieve secret
      env:
        CONJUR_ACCOUNT: conjur
        CONJUR_APPLIANCE_URL: https://pwclab.secretsmgr.cyberark.cloud
        CONJUR_AUTHN_LOGIN: host%2Fdata%2Fgithub-app
        CONJUR_API_KEY: 1pfa2en2cvh9q53xwymqc2fhehge303h3gt1jw2ppj1xweg0831exsd7
      run: |
        set -e
 
        echo "==============================="
        echo "Logging into Conjur..."
        echo "Account: $CONJUR_ACCOUNT"
        echo "Appliance URL: $CONJUR_APPLIANCE_URL"
        echo "Authn Login: $CONJUR_AUTHN_LOGIN"
        echo "==============================="
 
        echo "Authenticating..."
 
        FULL_AUTHN_URL=$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate
        echo "Calling authn URL: $FULL_AUTHN_URL"
 
        # RESPONSE=$(curl -i -s -w "\n%{http_code}" \
        #   --request POST \
        #   --data "$CONJUR_API_KEY" \
        #   "$FULL_AUTHN_URL")
         AUTHN_TOKEN=$(curl -s -k --request POST \
         --data "$CONJUR_API_KEY" \
         "$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate" \
         | base64 | tr -d '\r\n')
 
        echo "Full /authenticate response:"
        echo "$AUTHN_TOKEN"
 
        # BODY=$(echo "$RESPONSE" | sed '$d')
        # STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
 
        # if [ "$STATUS_CODE" != "200" ]; then
        #   echo "Authentication failed"
        #   echo "Status: $STATUS_CODE"
        #   echo "Body:"
        #   echo "$BODY"
        #   exit 1
        # fi
 
        # AUTHN_TOKEN=$(echo "$BODY" | base64 | tr -d '\r\n')
        # echo "$AUTHN_TOKEN"
        #::add-mask::
        echo "Authentication successful"
        echo "=============================="
 
        echo "Fetching secret...."
 
        #RAW_PATH="c"

 
        #SECRET_URL=$CONJUR_APPLIANCE_URL/api/secrets/$CONJUR_ACCOUNT/variable/data/vault/conjurtest/conjurtest/password
        
        #echo "Secret fetch URL: $SECRET_URL"
 
        #SECRET=$(curl -s -w "\n%{http_code}" \
        #  -H "Authorization: Token token=\"$AUTHN_TOKEN\"" \
        #  "$CONJUR_APPLIANCE_URL/api/secrets/$CONJUR_ACCOUNT/variable/data/vault/conjurtest/conjurtest/password")
        SECRET=$(curl -s -k --header "Authorization: Token token=\"$AUTHN_TOKEN\"" \
        "$CONJUR_APPLIANCE_URL/api/secrets/$CONJUR_ACCOUNT/variable/data%2Fvault%2Fconjurtest%2Fconjurtest%2Faddress")
 
        SECRET_VALUE=$(echo "$SECRET" | head -n1)
        SECRET_STATUS=$(echo "$SECRET" | tail -n1)
 
        #echo "Secret fetch status: $SECRET_STATUS"
        # if [ "$SECRET_STATUS" != "200" ]; then
        #   echo "Failed to fetch secret"
        #   echo "Response:"
        #   echo "$SECRET"
        #   exit 1
        # fi
        
        echo "Retrieved secret: $SECRET_VALUE"
